install.packages("twitteR", dependencies = TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("purrr", dependencies = TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("scales", dependencies = TRUE)
install.packages("stringr", dependencies = TRUE)
install.packages("tidytext", dependencies = TRUE)
install.packages("readr", dependencies = TRUE)
